### get tooele tech route

GET http://localhost:3001/ttech HTTP/1.1

### get the root path /
 GET http://localhost:3001/ HTTP/1.1

### get all students
 GET http://localhost:3001/students HTTP/1.1

### get single student
 GET http://localhost:3001/students/6541603171604ce77e51c9e3 HTTP/1.1

### create one student
POST http://localhost:3001/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "Walker",
    "email": "pwalker@test.com",
    "age": 29,
    "currentCollege": "BYU-Idaho"
}
### update one student
PATCH http://localhost:3001/students HTTP/1.1
### delete one student
DELETE http://localhost:3001/students HTTP/1.1
